<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerTableSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                "id" => 1,
                "first_name" => "Olivia",
                "last_name" => "Carter",
                "email" => "olivia.carter@example.com",
                "phone" => "+1 415-555-0101",
                "job_title" => "Account Executive",
                "department" => "Sales",
                "city" => "San Francisco",
                "country" => "United States",
                "status" => "active",
                "created_at" => "2024-03-12 10:05:00",
                "updated_at" => "2024-03-12 10:05:00"
            ],
            [
                "id" => 2,
                "first_name" => "Ethan",
                "last_name" => "Brooks",
                "email" => "ethan.brooks@example.com",
                "phone" => "+44 20 7946 0002",
                "job_title" => "Sales Manager",
                "department" => "Sales",
                "city" => "London",
                "country" => "United Kingdom",
                "status" => "active",
                "created_at" => "2024-04-02 14:21:00",
                "updated_at" => "2024-04-02 14:21:00"
            ],
            [
                "id" => 3,
                "first_name" => "Ava",
                "last_name" => "Mitchell",
                "email" => "ava.mitchell@example.com",
                "phone" => "+1 212-555-0103",
                "job_title" => "Marketing Specialist",
                "department" => "Marketing",
                "city" => "New York",
                "country" => "United States",
                "status" => "active",
                "created_at" => "2024-05-18 09:12:00",
                "updated_at" => "2024-05-18 09:12:00"
            ],
            [
                "id" => 4,
                "first_name" => "Liam",
                "last_name" => "Hughes",
                "email" => "liam.hughes@example.com",
                "phone" => "+61 2 5550 0104",
                "job_title" => "Software Engineer",
                "department" => "Engineering",
                "city" => "Sydney",
                "country" => "Australia",
                "status" => "active",
                "created_at" => "2024-06-07 11:40:00",
                "updated_at" => "2024-06-07 11:40:00"
            ],
            [
                "id" => 5,
                "first_name" => "Sophia",
                "last_name" => "Turner",
                "email" => "sophia.turner@example.com",
                "phone" => "+353 1 555 0105",
                "job_title" => "Support Agent",
                "department" => "Support",
                "city" => "Dublin",
                "country" => "Ireland",
                "status" => "active",
                "created_at" => "2024-06-28 08:33:00",
                "updated_at" => "2024-06-28 08:33:00"
            ],
            [
                "id" => 6,
                "first_name" => "Noah",
                "last_name" => "Ramirez",
                "email" => "noah.ramirez@example.com",
                "phone" => "+1 305-555-0106",
                "job_title" => "HR Generalist",
                "department" => "HR",
                "city" => "Miami",
                "country" => "United States",
                "status" => "active",
                "created_at" => "2024-07-12 15:02:00",
                "updated_at" => "2024-07-12 15:02:00"
            ],
            [
                "id" => 7,
                "first_name" => "Mia",
                "last_name" => "Bennett",
                "email" => "mia.bennett@example.com",
                "phone" => "+49 30 555 0107",
                "job_title" => "Product Manager",
                "department" => "Product",
                "city" => "Berlin",
                "country" => "Germany",
                "status" => "active",
                "created_at" => "2024-07-24 13:20:00",
                "updated_at" => "2024-07-24 13:20:00"
            ],
            [
                "id" => 8,
                "first_name" => "Mason",
                "last_name" => "Clark",
                "email" => "mason.clark@example.com",
                "phone" => "+31 20 555 0108",
                "job_title" => "Finance Analyst",
                "department" => "Finance",
                "city" => "Amsterdam",
                "country" => "Netherlands",
                "status" => "active",
                "created_at" => "2024-08-03 10:11:00",
                "updated_at" => "2024-08-03 10:11:00"
            ],
            [
                "id" => 9,
                "first_name" => "Isabella",
                "last_name" => "Foster",
                "email" => "isabella.foster@example.com",
                "phone" => "+33 1 55 50 0109",
                "job_title" => "Legal Counsel",
                "department" => "Legal",
                "city" => "Paris",
                "country" => "France",
                "status" => "inactive",
                "created_at" => "2024-08-22 16:45:00",
                "updated_at" => "2024-08-22 16:45:00"
            ],
            [
                "id" => 10,
                "first_name" => "Lucas",
                "last_name" => "Gray",
                "email" => "lucas.gray@example.com",
                "phone" => "+1 617-555-0110",
                "job_title" => "DevOps Engineer",
                "department" => "IT",
                "city" => "Boston",
                "country" => "United States",
                "status" => "active",
                "created_at" => "2024-09-05 09:55:00",
                "updated_at" => "2024-09-05 09:55:00"
            ],
            [
                "id" => 11,
                "first_name" => "Amelia",
                "last_name" => "Ward",
                "email" => "amelia.ward@example.com",
                "phone" => "+34 91 555 0111",
                "job_title" => "Content Strategist",
                "department" => "Marketing",
                "city" => "Madrid",
                "country" => "Spain",
                "status" => "prospect",
                "created_at" => "2024-09-21 12:00:00",
                "updated_at" => "2024-09-21 12:00:00"
            ],
            [
                "id" => 12,
                "first_name" => "James",
                "last_name" => "Cooper",
                "email" => "james.cooper@example.com",
                "phone" => "+41 44 555 0112",
                "job_title" => "Customer Success Mgr",
                "department" => "Support",
                "city" => "ZÃ¼rich",
                "country" => "Switzerland",
                "status" => "active",
                "created_at" => "2024-10-03 11:10:00",
                "updated_at" => "2024-10-03 11:10:00"
            ],
            [
                "id" => 13,
                "first_name" => "Charlotte",
                "last_name" => "Diaz",
                "email" => "charlotte.diaz@example.com",
                "phone" => "+1 206-555-0113",
                "job_title" => "UX Designer",
                "department" => "Product",
                "city" => "Seattle",
                "country" => "United States",
                "status" => "active",
                "created_at" => "2024-10-19 14:36:00",
                "updated_at" => "2024-10-19 14:36:00"
            ],
            [
                "id" => 14,
                "first_name" => "Benjamin",
                "last_name" => "Price",
                "email" => "benjamin.price@example.com",
                "phone" => "+65 6555 0114",
                "job_title" => "Solutions Architect",
                "department" => "Engineering",
                "city" => "Singapore",
                "country" => "Singapore",
                "status" => "active",
                "created_at" => "2024-11-02 10:28:00",
                "updated_at" => "2024-11-02 10:28:00"
            ],
            [
                "id" => 15,
                "first_name" => "Harper",
                "last_name" => "Reed",
                "email" => "harper.reed@example.com",
                "phone" => "+1 416-555-0115",
                "job_title" => "Data Analyst",
                "department" => "Finance",
                "city" => "Toronto",
                "country" => "Canada",
                "status" => "inactive",
                "created_at" => "2024-11-18 16:15:00",
                "updated_at" => "2024-11-18 16:15:00"
            ],
            [
                "id" => 16,
                "first_name" => "Henry",
                "last_name" => "Powell",
                "email" => "henry.powell@example.com",
                "phone" => "+46 8 555 0116",
                "job_title" => "IT Support Specialist",
                "department" => "IT",
                "city" => "Stockholm",
                "country" => "Sweden",
                "status" => "active",
                "created_at" => "2024-12-01 09:05:00",
                "updated_at" => "2024-12-01 09:05:00"
            ],
            [
                "id" => 17,
                "first_name" => "Evelyn",
                "last_name" => "Rivera",
                "email" => "evelyn.rivera@example.com",
                "phone" => "+52 55 5550 0117",
                "job_title" => "QA Engineer",
                "department" => "Engineering",
                "city" => "Mexico City",
                "country" => "Mexico",
                "status" => "prospect",
                "created_at" => "2024-12-19 13:49:00",
                "updated_at" => "2024-12-19 13:49:00"
            ],
            [
                "id" => 18,
                "first_name" => "Alexander",
                "last_name" => "Morris",
                "email" => "alexander.morris@example.com",
                "phone" => "+81 3 5550 0118",
                "job_title" => "Partnerships Lead",
                "department" => "Sales",
                "city" => "Tokyo",
                "country" => "Japan",
                "status" => "active",
                "created_at" => "2025-01-07 10:22:00",
                "updated_at" => "2025-01-07 10:22:00"
            ],
            [
                "id" => 19,
                "first_name" => "Abigail",
                "last_name" => "Jenkins",
                "email" => "abigail.jenkins@example.com",
                "phone" => "+55 11 5550 0119",
                "job_title" => "Office Manager",
                "department" => "Operations",
                "city" => "SÃ£o Paulo",
                "country" => "Brazil",
                "status" => "inactive",
                "created_at" => "2025-02-11 11:30:00",
                "updated_at" => "2025-02-11 11:30:00"
            ],
            [
                "id" => 20,
                "first_name" => "Michael",
                "last_name" => "Scott",
                "email" => "michael.scott@example.com",
                "phone" => "+61 3 5550 0120",
                "job_title" => "Regional Director",
                "department" => "Operations",
                "city" => "Melbourne",
                "country" => "Australia",
            ]
        ];

        DB::table('customers')->insert($customers);
    }
}
